services:
  postgres:
    image: postgres:latest
    container_name: postgres_sparky
    restart: always
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "6006:5432"
    volumes:
      - ${DOCKER_VOLUME}:/var/lib/postgresql/data
      - ./docs/script:/docker-entrypoint-initdb.d
    networks:
      - app-network

  node:
    container_name: "api-treinototal-sparky"
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3006:3000"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
